theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - typescript_learning.md
  - node_red_learning.md
  - english_learning.md
  - bak.md